### ISSUE TITLE
mar.js also gets identified as a *.mar file

### ISSUE THREAD

**Issue by kevinramharak** [PJB3005/much-assembly-required-vscode#1]
https://github.com/PJB3005/much-assembly-required-vscode/blob/d5de530c90c148d706157f2b6646897b92c64c7a/package.json#L31

Maybe this is a regular expression? then it should be `.*\.mar$` right?

**Comment by kevinramharak** [comment]
Never mind, it seems that all my files are being parsed by the extension. Ill just disable it for now

**Comment by PJB3005** [comment]
Just fixed this with 0a22b26a88d64cea1ed8bcddbc676542ace4959b, and I published `0.1.2`.
